apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-manifests
  namespace: argocd
spec:
  project: travel-guide-project
  source:
    repoURL: 'https://github.com/ceztro/ArgoCD_GitOps.git'
    targetRevision: dev
    path: 'travel_guide/manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: travel-guide-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncWave: "1"