apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-guide-deployment
  namespace: travel-guide
  labels:
    app: travel-guide
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travel-guide
  template:
    metadata:
      labels:
        app: travel-guide
    spec:
      containers:
      - name: travel-guide-container
        image: 871548798187.dkr.ecr.us-east-1.amazonaws.com/travel_guide:1.0
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

