apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["deployments", "services", "pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-binding
subjects:
  - kind: User
    name: github-runner-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-runner
  apiGroup: rbac.authorization.k8s.io