# Namespace for the resources
namespace: travel-guide-namespace

# Application-specific values
appName: travel-guide
replicas: 3

# Container values
containerName: travel-guide-container
containerPort: 5000

# Image-related values
image:
  repository: 871548798187.dkr.ecr.us-east-1.amazonaws.com/travel_guide
  tag: "1.4"
  pullPolicy: Always

# Service values
service:
  type: LoadBalancer
  port: 80

# Service account values
serviceAccount:
  create: true

aws:
  PodRoleName: arn:aws:iam::871548798187:role/pod-role
  accountId: 871548798187


ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
  hosts:
    - host: travel-guide.com
      paths:
        - /
  certificateArn: arn:aws:acm:region:account-id:certificate/certificate-id
  tlsSecretName: travel-guide-tls
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80