# Namespace for the resources
namespace: travel-guide-namespace

# Application-specific values
appName: travel-guide
replicas: 3

# Container values
containerName: travel-guide-container
containerPort: 5000

# Image-related values
image:
  repository: 871548798187.dkr.ecr.us-east-1.amazonaws.com/travel_guide
  tag: 06e79e8ea3ec980b103dfa4489a51c4f4de643cf
  pullPolicy: Always

# Service values
service:
  type: LoadBalancer
  port: 80

# Service account values
serviceAccount:
  create: true

aws:
  PodRoleName: arn:aws:iam::871548798187:role/pod-role
  AlbControllerRoleName: arn:aws:iam::871548798187:role/k8s_alb_role

ALBserviceAccount: {}

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb

  hosts:
    - host: travel-guide.com
      paths:
        - /
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80