apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ALBserviceAccount.name | default "aws-load-balancer-controller" }}
  namespace: {{ .Values.ALBserviceAccount.namespace | default "kube-system" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.AlbControllerRoleName }}