{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "travel_guide.fullname" $ }}  # Use $ for root context
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          {{- range $p := $host.paths }}
          - path: {{ $p }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "travel_guide.fullname" $ }}  # Use $ for root context
                port:
                  number: {{ $p.port | default $.Values.service.port }}  # Use $ to access the root context for .Values.service.port
          {{- end }}
    {{- end }}
{{- end }}