{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "travel_guide.fullname" . }}  
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}  # Directly access the first host
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0] }}  # Directly access the first path
            pathType: Prefix
            backend:
              service:
                name: {{ include "travel_guide.fullname" . }}  
                port:
                  number: {{ .Values.service.port }}
{{- end }}