apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "travel_guide.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.roleName }}
automountServiceAccountToken: true