apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "travel_guide.serviceAccountName" . }}
  annotations:
    description: "ServiceAccount for fetching secrets from AWS Secrets Manager"
    eks.amazonaws.com/role-arn: {{ .Values.roleName }}
automountServiceAccountToken: true