apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.PodServiceAccount.name | default "pod-service-account" }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.PodRoleName }}
automountServiceAccountToken: true